Zach Sosana Bio
lirantal/nodejssecurity pull request #6
Opened 2017-01-06 19:14 UTC by SOSANA

2017-01-06 22:23 UTC, lirantal requested changes
probably should fix the missing space in the last sentence: `@thesosana`or

2017-01-08 22:44 UTC, lirantal commented
@SOSANA FYI you might want to fix the typo in your bio

2017-01-09 22:30 UTC, SOSANA commented
@lirantal fixed spacing issue.

2017-01-10 14:17 UTC, lirantal commented
Great, thanks!

2017-01-10 14:17 UTC, merged